### ISSUE TITLE
Project won't compile, Visual studio gets stuck at an infinite loop.

### ISSUE THREAD

**Issue by Moonstrous** [nCine/nCine-libraries#1]
=======================================
Some information first : - OS : Windows 10
- IDE : Visual Studio 2019 Community edition (latest version)
- CMake (latest version)
========================================
Whenever i try to compile the nCine-libraries project (after configuring and generating), it starts looping at : vbc.exe access is denied (Can't figure out which project specifically as VS is stuck and I end up needing to end its process via Task Manager.
Anyways, something for sure : The source files don't show up on Visual studio, and when i head over to "ExternalProject\build" multiple folders are empty ... I tried downloading the specific tars (from the links in Stamp) and extracting them to source but to no avail.
- Thanks for your time and effort ! Can't wait for your response.

**Comment by encelo** [comment]
Hi @DProBoy, and thanks for your feedback.

I have compiled the libraries and the rest of the projects on many different machines with Windows 10, with both VS2017 and VS2019 and with different versions of CMake (both from the command line and through the GUI) and I have never seen something like that, to be honest.

Have you tried to update or repair your Visual Studio 2019 installation?
Have you tried to compile any other C++ code with your current Visual Studio 2019 installation?

**Comment by Moonstrous** [comment]
Yes I have, I'm not really sure what to do to tackle this issue ... is it perfectly normal for some of the ExternalProject/Source folders to be empty ? I've followed all the steps that have been specified in nCine's website.

**Comment by encelo** [comment]
A workaround could be for you to grab the libraries already compiled by the _continuous integration_ system here: https://github.com/nCine/nCine-libraries-artifacts/branches/all

**Comment by Moonstrous** [comment]
Thanks ! So far the nCine project has generated successfully, going to try to compile it now !
I'd also like to say (even though this mightn't belong in issues) that I'm thankful for the effort you put into this game engine ! Whilst (I'm sorry if I offended you by saying this) there are many more complex and "powerful" 2D game engines out there than nCine, I still think that it's quite readable and easy to wrap your mind around, the code looks, and IS structured cleanly. (Well, I'm not a big fan of the project structure ...) The code base isn't too large, and thus, nCine is perfect for people interested in learning game engine programming and design, it serves as a reference in many ways. I feel like that is its strong point :) ... Anyways, nCine successfully compiled and the apptest_particles is running flawlessly ! Please keep up the awesome work, and thanks for all the time and effort that you've put in to make nCine.
I'll continue to look into fixing my issues regarding nCine-libraries.

**Comment by encelo** [comment]
Yes, exactly, you have spotted one of the strong points of the project, in my opinion: the fact that it is small enough to serve as a learning and experimenting tool. :wink: 
And that's also one of the points I tried to highlight on the website: https://ncine.github.io/why/

**Comment by Moonstrous** [comment]
Anyways, shall I close this issue ?

**Comment by encelo** [comment]
Let's close it for now but please let me know about your progress with compiling `nCine-libraries`.
Also, if you haven't done it already, feel free to join the Discord server (https://discord.gg/495ab6Y) to talk with me and the rest of the users. :)

**Comment by Moonstrous** [comment]
Will do so as soon as possible, thanks for your time ! :)
